import { ArrowUpRight, Bell, CircleGauge, WalletCards, Zap } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { AnimatedHeading, AnimatedText } from '../components/AnimatedHeading'
import { PhoneMockup } from '../components/VisualPlaceholders'

export const featureSlugs = ['tarjetas', 'notificaciones', 'automatizaciones', 'analitica'] as const
export type FeatureSlug = typeof featureSlugs[number]

type ProductVisual = 'card' | 'notification' | 'automation' | 'analytics'
type FeatureProfile = {
  label: string
  eyebrow: string
  title: React.ReactNode
  intro: string
  icon: LucideIcon
  promise: string
  description: string
  productVisual: ProductVisual
  productLabel: string
  scene: { src: string; alt: string; caption: string }
  principles: { title: string; text: string }[]
  uses: { title: string; text: string }[]
}

const profiles: Record<FeatureSlug, FeatureProfile> = {
  tarjetas: {
    label: 'Tarjetas digitales', eyebrow: 'Resultado / clientes reconocibles', title: <>Haz que cada visita<br/><span>cuente para volver.</span></>, intro: 'Deja de tratar cada compra como una historia nueva. Conserva el avance de cada cliente y dale una razón clara para continuar la relación.', icon: WalletCards, promise: 'Que quien ya te eligió tenga un motivo visible para regresar.', description: 'La tarjeta no es el resultado. Es la infraestructura para reconocer a quien vuelve, hacer visible su avance y mantener la relación disponible después de la visita.', productVisual: 'card', productLabel: 'Tarjeta Taply en Wallet', scene: { src: '/images/fidelio-product-tarjetas.webp', alt: 'Clienta usando su teléfono en una cafetería local después de una compra', caption: 'Una buena visita deja una razón visible para que la siguiente ocurra.' }, principles: [{ title: 'No empiezas de cero', text: 'Cada visita conserva el avance y el contexto de la relación.' }, { title: 'El cliente ve el siguiente paso', text: 'El beneficio deja de ser abstracto y se vuelve una razón concreta para volver.' }, { title: 'La relación sigue disponible', text: 'El programa vive donde el cliente ya guarda lo importante.' }], uses: [{ title: 'Reconoce frecuencia', text: 'Haz visible el progreso de quienes ya eligieron tu negocio.' }, { title: 'Construye recurrencia', text: 'Convierte compras repetidas en una relación que vale la pena continuar.' }, { title: 'Premia lealtad real', text: 'Da valor a quien vuelve, no solo a quien llega por primera vez.' }],
  },
  notificaciones: {
    label: 'Notificaciones', eyebrow: 'Resultado / una razón para volver', title: <>Da una razón.<br/><span>Haz que vuelvan.</span></>, intro: 'No necesitas más mensajes. Necesitas aparecer con una razón útil justo cuando una próxima visita todavía es una decisión abierta.', icon: Bell, promise: 'Que una buena experiencia no se enfríe al salir por la puerta.', description: 'Las notificaciones no venden tecnología. Mantienen tu negocio presente con un motivo concreto para volver: un beneficio, una novedad o un momento que importa.', productVisual: 'notification', productLabel: 'Notificación de Taply en Wallet', scene: { src: '/images/fidelio-product-notificaciones.webp', alt: 'Cliente revisando una notificación mientras sale de una cafetería local', caption: 'El mensaje llega cuando todavía puede cambiar la siguiente decisión.' }, principles: [{ title: 'Un motivo, no ruido', text: 'Cada mensaje tiene una razón clara para ser visto.' }, { title: 'En el momento correcto', text: 'El valor aparece cuando puede influir en una siguiente visita.' }, { title: 'Con el contexto del cliente', text: 'La relación anterior hace que el mensaje tenga más sentido.' }], uses: [{ title: 'Recupera una visita', text: 'Dale una razón concreta a quien dejó de pasar.' }, { title: 'Activa momentos tranquilos', text: 'Crea demanda cuando más la necesitas.' }, { title: 'Haz visible el valor', text: 'Recuerda beneficios que el cliente ya ganó.' }],
  },
  automatizaciones: {
    label: 'Automatizaciones', eyebrow: 'Resultado / relación que sigue', title: <>Cuida el regreso.<br/><span>Sin perseguirlo.</span></>, intro: 'La relación no debería depender de que alguien se acuerde de escribir. Define los momentos que importan y deja que Taply abra el siguiente paso.', icon: Zap, promise: 'Que el hábito se sostenga incluso cuando el equipo está ocupado.', description: 'Las automatizaciones hacen que las acciones reales tengan continuidad. Cuando alguien visita, se aleja o alcanza un beneficio, el negocio puede responder a tiempo.', productVisual: 'automation', productLabel: 'Automatización de Taply en Wallet', scene: { src: '/images/fidelio-product-automatizaciones.webp', alt: 'Dueño de restaurante dando la bienvenida a una clienta que regresa', caption: 'La mejor automatización se siente como una relación bien cuidada.' }, principles: [{ title: 'La relación tiene memoria', text: 'Una visita o un periodo sin volver puede abrir el siguiente momento.' }, { title: 'El negocio responde a tiempo', text: 'El motivo llega cuando la decisión todavía importa.' }, { title: 'Menos tareas, más continuidad', text: 'El equipo mantiene el foco en atender, no en perseguir clientes.' }], uses: [{ title: 'Después de una visita', text: 'Convierte un buen momento en una razón para regresar.' }, { title: 'Antes de que se pierda el hábito', text: 'Recupera a quien dejó de volver con un motivo específico.' }, { title: 'Cuando hay oportunidad', text: 'Activa un beneficio antes de que el cliente elija otro lugar.' }],
  },
  analitica: {
    label: 'Analítica', eyebrow: 'Resultado / retorno entendible', title: <>Entiende el regreso.<br/><span>Repítelo mejor.</span></>, intro: 'No basta con saber que una campaña se envió. Necesitas entender qué hace que la gente vuelva y qué vale la pena repetir.', icon: CircleGauge, promise: 'Que tus decisiones se basen en retorno, no en intuición.', description: 'La analítica convierte el historial de visitas y activaciones en una forma clara de aprender: quién vuelve, qué los activa y dónde está la siguiente oportunidad.', productVisual: 'analytics', productLabel: 'Dashboard de Taply', scene: { src: '/images/fidelio-product-analitica.webp', alt: 'Dueño de un negocio local revisando métricas en su laptop', caption: 'Cuando el regreso se entiende, el siguiente paso se decide mejor.' }, principles: [{ title: 'Ve la relación completa', text: 'Entiende la frecuencia, no solo la venta aislada.' }, { title: 'Aprende de cada activación', text: 'Compara qué motivos generan una siguiente visita.' }, { title: 'Repite con intención', text: 'Elige el próximo incentivo con señales reales, no con intuición.' }], uses: [{ title: 'Clientes que regresan', text: 'Reconoce quién ya está construyendo un hábito contigo.' }, { title: 'Campañas que funcionan', text: 'Invierte energía en los motivos que de verdad activan retorno.' }, { title: 'Beneficios que convienen', text: 'Descubre qué recompensa merece seguir siendo parte del programa.' }],
  },
}

export function isFeatureSlug(value: string): value is FeatureSlug { return featureSlugs.includes(value as FeatureSlug) }

function FeatureProductVisual({ type, label }: { type: ProductVisual; label: string }) {
  if (type === 'analytics') return <figure className="w-full overflow-hidden rounded-[28px] border border-border bg-[#e8ebe4] p-8 md:p-12"><div className="flex aspect-[16/10] flex-col justify-between rounded-[18px] border border-foreground/15 bg-background p-6"><div className="flex items-center justify-between text-[11px] uppercase tracking-[0.18em] text-muted-foreground"><span>Taply / analítica</span><CircleGauge className="h-5 w-5 text-[#2c8f58]" strokeWidth={1.5}/></div><div><p className="font-display text-3xl tracking-[-.04em] md:text-4xl">Dashboard en construcción.</p><p className="mt-4 max-w-md text-sm leading-relaxed text-muted-foreground">Este espacio recibirá el dashboard de Taply con métricas de visitas, campañas y retorno.</p></div><p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">Próximo visual de producto</p></div><figcaption className="mt-5 text-xs uppercase tracking-[0.16em] text-muted-foreground">{label}</figcaption></figure>
  return <div className="flex flex-col items-center"><PhoneMockup variant={type === 'card' ? 'card' : 'notification'} label={label}/>{type === 'automation' && <p className="mt-3 text-xs uppercase tracking-[0.16em] text-muted-foreground">Visita → regla → mensaje</p>}</div>
}

export function FeatureLandingPage({ slug }: { slug: FeatureSlug }) {
  const feature = profiles[slug]
  const Icon = feature.icon
  return <main className="min-h-screen bg-background px-5 pb-20 pt-28 sm:px-8 md:px-12 md:pb-32 md:pt-36">
    <section className="grid grid-cols-12 items-end gap-10 pb-16 md:gap-12 md:pb-28"><div className="col-span-12 md:col-span-7"><p className="mb-8 text-[11px] uppercase tracking-[0.2em] text-muted-foreground">{feature.eyebrow}</p><AnimatedHeading as="h1" className="font-display text-[clamp(2rem,5vw,4.5rem)] font-medium leading-[.98] tracking-[-.045em]">{feature.title}</AnimatedHeading></div><AnimatedText className="col-span-12 self-end max-w-xl text-base leading-relaxed text-muted-foreground md:col-span-4 md:col-start-9 md:pb-2">{feature.intro}</AnimatedText></section>
    <section className="grid grid-cols-12 items-center gap-10 border-t border-border pt-16 md:gap-12 md:pt-20"><div className="col-span-12 flex justify-center md:col-span-5"><FeatureProductVisual type={feature.productVisual} label={feature.productLabel}/></div><div className="col-span-12 md:col-span-6 md:col-start-7"><Icon className="h-6 w-6 text-[#2c8f58]" strokeWidth={1.5}/><h2 className="mt-8 font-display text-[clamp(2.25rem,4vw,4.2rem)] font-medium leading-[1] tracking-[-.04em]">{feature.promise}</h2><p className="mt-7 max-w-xl text-base leading-relaxed text-muted-foreground">{feature.description}</p><a href="https://cal.com/alan-goldstein-z1hmxl/demo-fidelio" className="mt-9 inline-flex items-center gap-3 rounded-full bg-foreground py-2 pl-6 pr-2 text-sm font-medium text-white transition hover:bg-foreground/85">Reserva una demo<span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#9ae8af] text-foreground"><ArrowUpRight className="h-4 w-4"/></span></a></div></section>
    <section className="mt-20 grid grid-cols-1 gap-4 md:mt-28 md:grid-cols-12"><figure className="overflow-hidden rounded-[28px] bg-[#e8ebe4] md:col-span-7"><img className="aspect-[16/10] h-full w-full object-cover" src={feature.scene.src} alt={feature.scene.alt}/><figcaption className="px-6 py-5 text-sm leading-relaxed text-muted-foreground">{feature.scene.caption}</figcaption></figure><div className="rounded-[28px] bg-[#e8ebe4] p-7 md:col-span-5 md:p-10"><p className="text-[11px] uppercase tracking-[0.2em] text-muted-foreground">Cómo funciona</p><div className="mt-10 space-y-7">{feature.principles.map(({ title, text }, index) => <div key={title} className="border-t border-foreground/15 pt-5"><span className="text-xs text-muted-foreground">0{index + 1}</span><h3 className="mt-3 text-xl font-medium tracking-[-.025em]">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{text}</p></div>)}</div></div></section>
    <section className="mt-20 bg-foreground px-7 py-14 text-white md:mt-28 md:px-12 md:py-20"><div className="grid grid-cols-12 gap-10 md:gap-12"><div className="col-span-12 md:col-span-5"><p className="text-[11px] uppercase tracking-[0.2em] text-white/45">Casos de uso</p><h2 className="mt-7 font-display text-[clamp(2.25rem,4vw,4rem)] font-medium leading-[1] tracking-[-.04em]">Una función.<br/><span className="text-white/40">Distintos momentos.</span></h2></div><div className="col-span-12 md:col-span-6 md:col-start-7"><div className="border-t border-white/15">{feature.uses.map(({ title, text }) => <div key={title} className="border-b border-white/15 py-6"><h3 className="text-xl font-medium">{title}</h3><p className="mt-3 max-w-md text-sm leading-relaxed text-white/55">{text}</p></div>)}</div></div></div></section>
    <section className="mt-20 flex flex-col items-start justify-between gap-7 border-t border-border pt-10 md:mt-28 md:flex-row md:items-end"><div><p className="text-[11px] uppercase tracking-[0.2em] text-muted-foreground">Taply / {feature.label}</p><h2 className="mt-5 font-display text-[clamp(2.25rem,4vw,4rem)] font-medium leading-[1] tracking-[-.04em]">Diseñemos el próximo<br/>motivo para volver.</h2></div><a href="https://cal.com/alan-goldstein-z1hmxl/demo-fidelio" className="inline-flex items-center gap-3 rounded-full bg-foreground py-2 pl-6 pr-2 text-sm font-medium text-white transition hover:bg-foreground/85">Reserva una demo<span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#9ae8af] text-foreground"><ArrowUpRight className="h-4 w-4"/></span></a></section>
  </main>
}
