import { Activity, ArrowDown, ArrowUpRight, Bell, Check, ChevronDown, CircleGauge, MapPin, MessageSquareText, Play, Send, Smartphone, Sparkles, WalletCards, Zap } from 'lucide-react'
import { useEffect, useState } from 'react'
import { AnimatedHeading, AnimatedText, MaskedImage } from '../components/AnimatedHeading'
import { Header } from '../components/Header'
import { CardPlaceholder, PhoneMockup, ScenePlaceholder } from '../components/VisualPlaceholders'
import { FeaturesPage, IndustriesPage, ProductPage } from './pages'

const BASE = 'https://qclay.design/lovable/pelmatech/'

function Hero() {
  return <section id="home" className="relative min-h-[780px] h-screen w-full overflow-hidden bg-[#11130f] text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_68%_32%,rgba(180,255,205,.2),transparent_24%),linear-gradient(120deg,#151a15_0%,#223126_45%,#10130f_100%)]"/><div className="absolute -right-24 top-28 h-[580px] w-[580px] rounded-full border border-white/10 opacity-70"/><div className="absolute right-[-80px] top-[180px] h-[430px] w-[430px] rounded-full border border-[#9ae8af]/25"/><div className="absolute right-[90px] top-[280px] h-[260px] w-[260px] rounded-full border border-[#9ae8af]/20"/><div className="absolute right-[170px] top-[360px] h-[100px] w-[100px] rounded-full bg-[#b6f3c0]/20 blur-2xl"/><div className="absolute right-[14%] top-[100px] hidden xl:block"><PhoneMockup label="Visual principal / tarjeta Fidelio"/></div><div className="absolute inset-0 bg-gradient-to-t from-black/35 via-transparent to-transparent"/><div className="absolute inset-0 flex flex-col justify-end px-8 pb-16 md:px-12"><div className="grid grid-cols-12 items-end gap-8"><div className="col-span-12 max-w-3xl md:col-span-8"><p className="mb-10 text-[11px] uppercase tracking-[0.2em] text-white/55">Fidelio / fidelización en el Wallet</p><AnimatedHeading as="h1" className="font-display font-medium leading-[1.02] tracking-[-.035em]"><span className="block text-6xl md:text-[72px]">Convierte clientes<br/>ocasionales en<br/><span className="text-white/45">habituales.</span></span></AnimatedHeading><AnimatedText className="mt-8 max-w-xl text-white/75"><span className="block text-lg leading-relaxed md:text-[21px]">Aumenta la frecuencia de visita, el retorno y el ROI con un motor de marketing nativo de Wallet. Sin app, sin complicar tu operación.</span></AnimatedText></div><div className="col-span-12 flex items-center gap-6 md:col-span-4 md:justify-end"><a href="#demo" className="flex items-center gap-3 rounded-full bg-white py-2 pl-6 pr-2 text-sm font-medium text-foreground transition hover:bg-white/90">Reserva una demo<span className="flex h-9 w-9 items-center justify-center rounded-full bg-foreground text-white"><ArrowUpRight className="h-4 w-4"/></span></a><a href="#como-funciona" className="flex items-center gap-1 text-sm font-medium text-white">Ver cómo funciona <ArrowDown className="h-4 w-4"/></a></div></div><div className="mt-12 flex items-center justify-between border-t border-white/20 pt-5 text-[12px] uppercase tracking-[0.2em] text-white/60"><span>Más frecuencia / más retorno</span><span className="hidden md:inline">01 / 08</span><span>Scroll to explore</span></div></div></section>
}

function WhatWeDo() {
  return <section id="producto" className="px-8 py-32 md:px-12"><div className="grid grid-cols-12 gap-12"><div className="col-span-12 md:col-span-7"><p className="mb-12 text-[11px] uppercase tracking-[0.2em] text-muted-foreground">Qué hacemos</p><AnimatedHeading className="font-display text-5xl font-medium leading-[1.02] tracking-[-.035em] md:text-7xl">Tarjetas de<br/>fidelización para<br/><span className="text-muted-foreground">negocios locales.</span></AnimatedHeading></div><AnimatedText className="col-span-12 self-end text-base leading-relaxed text-muted-foreground md:col-span-4 md:col-start-9 md:pb-2">Fidelio ayuda a negocios locales a convertir visitas ocasionales en clientes habituales: crea tarjetas de fidelización en el celular de tus clientes, activa su regreso y mide qué genera más retorno.</AnimatedText></div><div className="mt-24 grid grid-cols-1 gap-3 md:grid-cols-3"><ProductCard icon={WalletCards} number="01" title="El Wallet es el canal" text="La tarjeta vive donde tus clientes ya guardan cosas importantes: en su celular."/><ProductCard icon={Bell} number="02" title="La marca activa" text="Notificaciones, beneficios y recordatorios convierten una visita en un próximo paso."/><ProductCard icon={CircleGauge} number="03" title="El retorno se mide" text="Conecta campañas, recompensas y comportamiento para saber qué funciona."/></div></section>
}

function ProductCard({ icon: Icon, number, title, text }: { icon: typeof WalletCards; number: string; title: string; text: string }) { return <div className="min-h-[300px] border-t border-border p-8 md:border-r md:p-10 md:last:border-r-0"><div className="mb-20 flex items-center justify-between"><span className="text-xs text-muted-foreground">({number})</span><Icon className="h-5 w-5 text-muted-foreground" strokeWidth={1.5}/></div><h3 className="text-2xl font-medium tracking-[-.025em]">{title}</h3><p className="mt-4 max-w-xs text-sm leading-relaxed text-muted-foreground">{text}</p></div> }

function InstallSection() {
  const steps = [{ icon: Smartphone, title: 'Escanea', text: 'Tu cliente escanea el QR en caja o abre tu link de Fidelio.' }, { icon: WalletCards, title: 'Agrega', text: 'Elige Apple Wallet o Google Wallet y guarda la tarjeta con un toque.' }, { icon: Zap, title: 'Usa', text: 'La muestra en cada visita, recibe recompensas y vuelve a elegirte.' }]
  return <section id="como-funciona" className="bg-[#e8ebe4] px-8 py-32 md:px-12"><div className="grid grid-cols-12 gap-12"><div className="col-span-12 md:col-span-5"><p className="mb-12 text-[11px] uppercase tracking-[0.2em] text-muted-foreground">Cómo se instala</p><AnimatedHeading className="font-display text-5xl font-medium leading-[1.02] tracking-[-.035em] md:text-6xl">De QR a cliente<br/><span className="text-muted-foreground">habitual</span> en<br/>segundos.</AnimatedHeading><AnimatedText className="mt-10 max-w-sm text-base leading-relaxed text-muted-foreground">Ellos lo instalan, tú lo activas. La entrada es simple para el cliente y accionable para el negocio.</AnimatedText><div className="mt-12 hidden md:block"><ScenePlaceholder label="Escena real / caja" detail="Placeholder para foto de cliente escaneando el QR"/></div></div><div className="col-span-12 flex flex-col md:col-span-6 md:col-start-7">{steps.map(({ icon: Icon, title, text }, i) => <div key={title} className="flex gap-6 border-t border-foreground/15 py-8"><span className="mt-1 text-xs text-muted-foreground">0{i + 1}</span><div className="flex-1"><div className="flex items-center justify-between"><h3 className="text-2xl font-medium">{title}</h3><Icon className="h-5 w-5 text-muted-foreground" strokeWidth={1.5}/></div><p className="mt-3 max-w-md text-sm leading-relaxed text-muted-foreground">{text}</p></div></div>)}<div className="mt-10 flex items-center gap-3 rounded-2xl bg-white/70 p-5 text-sm text-muted-foreground"><Check className="h-4 w-4 text-[#2c8f58]"/>Sin app. Sin cuenta adicional. Sin cambiar tu operación.</div></div></div></section>
}

function ProgramsSection() { const programs = [{ title: 'Tarjeta de sellos', text: 'Recompensa visitas o compras frecuentes con un beneficio claro.', accent: 'mint' as const }, { title: 'Tarjeta por puntos', text: 'Acumula puntos y canjéalos según las reglas de tu negocio.', accent: 'blue' as const }, { title: 'Tarjeta de evento', text: 'Comunica una experiencia, fecha, acceso o actualización desde un pass digital.', accent: 'sand' as const }]; return <section className="px-8 py-32 md:px-12"><div className="mb-20 grid grid-cols-12 gap-12"><div className="col-span-12 md:col-span-7"><p className="mb-12 text-[11px] uppercase tracking-[0.2em] text-muted-foreground">Programas de fidelización</p><AnimatedHeading className="font-display text-5xl font-medium leading-[1.02] tracking-[-.035em] md:text-6xl">Elige la tarjeta que<br/>mejor funciona para<br/><span className="text-muted-foreground">tu negocio.</span></AnimatedHeading></div><AnimatedText className="col-span-12 self-end text-base leading-relaxed text-muted-foreground md:col-span-4 md:col-start-9">Recompensa cada visita, acumula puntos por compra o comunica tus eventos con una tarjeta que vive dentro del Wallet.</AnimatedText></div><div className="grid grid-cols-1 gap-4 md:grid-cols-3">{programs.map((program, i) => <div key={program.title}><CardPlaceholder label={program.title} detail={program.text} tone={program.accent}/><span className="mt-3 block text-xs uppercase tracking-[0.16em] text-muted-foreground">Placeholder para tarjeta futura / uso {i + 1}</span></div>)}</div></section> }

function ActivationSection() { const features = [{ icon: Bell, eyebrow: 'Notificaciones', title: 'Envía el mensaje adecuado en el momento adecuado.', text: 'Instantáneas, programadas o basadas en ubicación para llegar directamente a la pantalla de bloqueo.' }, { icon: Zap, eyebrow: 'Automatizaciones', title: 'Automatiza tu marketing con un solo toque.', text: 'Configura reglas basadas en acciones reales y deja que Fidelio active el siguiente contacto.' }, { icon: CircleGauge, eyebrow: 'Analítica completa', title: 'Mide tu éxito y comprueba cómo vuelven.', text: 'Entiende el crecimiento del programa y decide qué hacer con cada segmento de clientes.' }]; return <section id="features" className="bg-foreground px-8 py-32 text-white md:px-12"><div className="grid grid-cols-12 gap-12"><div className="col-span-12 md:col-span-6"><p className="mb-12 text-[11px] uppercase tracking-[0.2em] text-white/45">Más que una tarjeta</p><AnimatedHeading className="font-display text-5xl font-medium leading-[1.02] tracking-[-.035em] md:text-7xl">El Wallet también<br/><span className="text-white/40">hace el trabajo.</span></AnimatedHeading></div><AnimatedText className="col-span-12 self-end text-base leading-relaxed text-white/50 md:col-span-4 md:col-start-9">La tarjeta es el medio. Hacer que el cliente vuelva es el resultado.</AnimatedText></div><div className="mt-24 grid grid-cols-1 border-t border-white/15 md:grid-cols-3">{features.map(({ icon: Icon, eyebrow, title, text }, i) => <div key={eyebrow} className="border-b border-white/15 py-10 md:border-b-0 md:border-r md:px-10 md:first:pl-0 md:last:border-r-0"><div className="mb-16 flex items-center justify-between"><span className="text-xs text-white/40">(0{i + 1})</span><Icon className="h-5 w-5 text-white/60" strokeWidth={1.5}/></div><p className="mb-4 text-[11px] uppercase tracking-[0.2em] text-white/45">{eyebrow}</p><AnimatedHeading as="h3" className="text-2xl font-medium leading-tight">{title}</AnimatedHeading><AnimatedText className="mt-4 max-w-xs text-sm leading-relaxed text-white/50">{text}</AnimatedText></div>)}</div></section> }

function IndustriesSection() { const industries = [{ name: 'Cafeterías', promise: 'Aumenta la frecuencia de cada visita.' }, { name: 'Bares', promise: 'Activa la próxima noche.' }, { name: 'Restaurantes', promise: 'Convierte una visita en una próxima reserva.' }, { name: 'Comercios', promise: 'Convierte compras en clientes habituales.' }, { name: 'Panaderías', promise: 'Convierte compras en hábito.' }, { name: 'Eventos', promise: 'Un pass digital para cada acceso.' }]; return <section id="industrias" className="px-8 py-32 md:px-12"><div className="grid grid-cols-12 gap-12"><div className="col-span-12 md:col-span-6"><p className="mb-12 text-[11px] uppercase tracking-[0.2em] text-muted-foreground">Mensajes por industria</p><AnimatedHeading className="font-display text-5xl font-medium leading-[1.02] tracking-[-.035em] md:text-6xl">Una lógica de<br/>producto. Distintos<br/><span className="text-muted-foreground">momentos de consumo.</span></AnimatedHeading></div><AnimatedText className="col-span-12 self-end text-base leading-relaxed text-muted-foreground md:col-span-4 md:col-start-9">La estructura se mantiene: tarjeta, comunicación, automatización y medición. Lo que cambia es el momento que activa el regreso.</AnimatedText></div><div className="mt-24 grid grid-cols-1 border-t border-border md:grid-cols-2">{industries.map((industry, i) => <a key={industry.name} href="#demo" className="group flex items-start gap-6 border-b border-border py-8 md:pr-12"><span className="text-xs text-muted-foreground">0{i + 1}</span><div className="flex-1"><div className="flex items-center justify-between gap-6"><h3 className="text-2xl font-medium">{industry.name}</h3><ArrowUpRight className="h-5 w-5 text-muted-foreground transition group-hover:-translate-y-1 group-hover:translate-x-1"/></div><p className="mt-3 text-sm text-muted-foreground">{industry.promise}</p></div></a>)}</div></section> }

function FAQSection() { const faqs = ['¿Mis clientes necesitan descargar una app?', '¿Cómo reemplaza Fidelio una tarjeta de sellos en papel?', '¿Qué tipo de notificaciones puedo enviar?', '¿Fidelio funciona con mi sistema de ventas?', '¿Cuánto tiempo toma lanzar el programa?']; const [open, setOpen] = useState(0); const answers = ['No. Las tarjetas viven dentro de Apple Wallet y Google Wallet. No hay nada que descargar ni otra cuenta que crear.', 'Cada sello o punto se actualiza cuando tu equipo escanea el QR del cliente. El avance queda guardado en tiempo real y no se pierde.', 'Puedes enviar notificaciones instantáneas, campañas programadas, recordatorios por fecha, mensajes por cercanía y activaciones basadas en comportamiento.', 'Sí. Fidelio puede funcionar de forma independiente, sin cambiar nada en caja. Para operaciones más grandes se pueden evaluar integraciones con POS o CRM.', 'Un local independiente puede quedar listo rápidamente. El tiempo depende de la tarjeta, la configuración de recompensas y los canales que quieras activar.']; return <section id="faq" className="bg-[#e8ebe4] px-8 py-32 md:px-12"><div className="grid grid-cols-12 gap-12"><div className="col-span-12 md:col-span-5"><p className="mb-12 text-[11px] uppercase tracking-[0.2em] text-muted-foreground">Preguntas frecuentes</p><AnimatedHeading className="font-display text-5xl font-medium leading-[1.02] tracking-[-.035em] md:text-6xl">Lo que necesitas<br/>saber antes<br/><span className="text-muted-foreground">de empezar.</span></AnimatedHeading></div><div className="col-span-12 md:col-span-6 md:col-start-7">{faqs.map((question, i) => <div key={question} className="border-t border-foreground/15 py-6"><button className="flex w-full items-center justify-between gap-6 text-left" onClick={() => setOpen(open === i ? -1 : i)}><span className="text-lg font-medium">{question}</span><ChevronDown className={`h-5 w-5 shrink-0 text-muted-foreground transition-transform ${open === i ? 'rotate-180' : ''}`}/></button>{open === i && <AnimatedText className="mt-4 max-w-xl text-sm leading-relaxed text-muted-foreground">{answers[i]}</AnimatedText>}</div>)}</div></div></section> }

function ClosingSection() { return <section id="demo" className="bg-[#131612] px-8 py-32 text-white md:px-12 md:py-40"><div className="grid grid-cols-12 gap-12"><div className="col-span-12 md:col-span-8"><p className="mb-12 text-[11px] uppercase tracking-[0.2em] text-white/45">Empieza a aumentar la frecuencia de visita</p><AnimatedHeading className="font-display text-5xl font-medium leading-[1.02] tracking-[-.035em] md:text-7xl">Convierte más visitas<br/>en clientes<br/><span className="text-white/40">habituales.</span></AnimatedHeading></div><div className="col-span-12 self-end md:col-span-3 md:col-start-10"><AnimatedText className="text-base leading-relaxed text-white/50">Reserva una demo y descubre qué programa, campaña y métrica tienen más sentido para tu negocio.</AnimatedText><a href="mailto:hola@fidelio.lat" className="mt-8 inline-flex items-center gap-3 rounded-full bg-white py-2 pl-6 pr-2 text-sm font-medium text-foreground transition hover:bg-white/90">Reserva una demo<span className="flex h-9 w-9 items-center justify-center rounded-full bg-foreground text-white"><ArrowUpRight className="h-4 w-4"/></span></a></div></div><div className="mt-32 grid grid-cols-2 gap-10 border-t border-white/15 pt-6 text-xs uppercase tracking-[0.2em] text-white/45 md:grid-cols-4"><span>Fidelio</span><span>Más frecuencia. Más retorno.</span><span>hola@fidelio.lat</span><span className="text-right">© 2025</span></div></section> }

function App() { const [hash, setHash] = useState(() => window.location.hash); useEffect(() => { const onHash = () => setHash(window.location.hash); addEventListener('hashchange', onHash); return () => removeEventListener('hashchange', onHash) }, []); const page = hash === '#producto' ? <ProductPage/> : hash === '#features' ? <FeaturesPage/> : hash === '#industrias' ? <IndustriesPage/> : <main><Hero/><WhatWeDo/><InstallSection/><ProgramsSection/><ActivationSection/><IndustriesSection/><FAQSection/><ClosingSection/></main>; return <div className="bg-background text-foreground"><Header/>{page}</div> }

export { App }
