import { ArrowUpRight, Bell, CircleGauge, WalletCards, Zap } from 'lucide-react'
import { industryProfiles } from './industry'
import { AnimatedHeading, AnimatedText } from '../components/AnimatedHeading'
import { CardPlaceholder, PhoneMockup, ScenePlaceholder } from '../components/VisualPlaceholders'
import type { ReactNode } from 'react'

const industries = [
  ['Cafeterías', 'Aumenta la frecuencia de cada visita.', 'Activa el happy hour, anuncia lo recién salido del horno o recupera a quien dejó de pasar.'],
  ['Bares', 'Activa la próxima noche.', 'Comunica tu próximo evento o envía una razón para volver antes de que el cliente decida dónde salir.'],
  ['Restaurantes', 'Convierte una visita en una próxima reserva.', 'Presenta un menú nuevo, llena un martes tranquilo o invita a volver a quienes ya disfrutaron tu mesa.'],
  ['Comercios', 'Convierte compras en clientes habituales.', 'Mantén tu marca presente entre una compra y la siguiente con beneficios y campañas relevantes.'],
  ['Panaderías', 'Convierte compras en hábito.', 'Haz visible la repetición y recupera el hábito de compra con sellos, puntos y mensajes directos.'],
  ['Eventos', 'Un pass digital para cada acceso.', 'Actualiza horarios, salas, accesos y experiencias desde la credencial que ya tiene el asistente.'],
]

export function ProductPage() {
  const capabilities = [
    { number: '01', label: 'Reconoce a quien vuelve', text: 'Conserva cada avance para que una visita no se pierda al salir por la puerta.', href: '#tarjetas', icon: WalletCards },
    { number: '02', label: 'Dales una razón para regresar', text: 'Aparece con un motivo útil antes de que la siguiente decisión se cierre.', href: '#notificaciones', icon: Bell },
    { number: '03', label: 'Sostén el hábito', text: 'Deja que los momentos importantes abran el siguiente paso sin tareas manuales.', href: '#automatizaciones', icon: Zap },
    { number: '04', label: 'Repite lo que funciona', text: 'Entiende qué beneficios, campañas y momentos generan un regreso real.', href: '#analitica', icon: CircleGauge },
  ]
  return <PageShell eyebrow="El resultado que buscas" title={<>Haz que volver sea<br/><span>parte de tu negocio.</span></>} intro="Reconoce a las personas que ya te eligieron, dales motivos para regresar y aprende qué hace que lo hagan.">
    <section className="grid grid-cols-12 items-center gap-10 border-t border-border pt-16 md:gap-12 md:pt-20"><div className="col-span-12 md:col-span-5"><figure className="overflow-hidden rounded-[28px]"><img className="aspect-[4/5] h-full w-full object-cover" src="/images/fidelio-product-tarjetas.webp" alt="Clienta usando su teléfono después de comprar en una cafetería local"/></figure></div><div className="col-span-12 md:col-span-6 md:col-start-7"><p className="text-[11px] uppercase tracking-[0.2em] text-muted-foreground">La infraestructura es el medio</p><h2 className="mt-7 font-display text-[clamp(2.25rem,4vw,4rem)] font-medium leading-[1] tracking-[-.04em]">Que tu próxima venta<br/><span className="text-muted-foreground">no empiece de cero.</span></h2><p className="mt-6 max-w-xl text-base leading-relaxed text-muted-foreground">Fidelio conserva la relación después de una visita, abre una razón relevante para volver y te ayuda a repetir lo que genera frecuencia.</p><div className="mt-10 flex justify-center md:justify-start"><PhoneMockup label="Tarjeta Fidelio en Apple Wallet"/></div></div></section>
    <section className="mt-20 border-t border-border pt-12 md:mt-28 md:pt-16"><div className="max-w-2xl"><p className="text-[11px] uppercase tracking-[0.2em] text-muted-foreground">Cómo se construye el regreso</p><h2 className="mt-6 font-display text-[clamp(2.25rem,4vw,4rem)] font-medium leading-[1] tracking-[-.04em]">Cuatro capacidades.<br/><span className="text-muted-foreground">Un resultado que se nota.</span></h2></div><div className="mt-12 grid grid-cols-1 gap-3 md:grid-cols-2">{capabilities.map(({ number, label, text, href, icon: Icon }) => <a key={label} href={href} className="group rounded-[22px] border border-border p-7 transition hover:border-foreground/35 md:p-9"><div className="flex items-center justify-between"><span className="text-xs text-muted-foreground">{number}</span><Icon className="h-5 w-5 text-[#2c8f58]" strokeWidth={1.5}/></div><h3 className="mt-16 text-2xl font-medium tracking-[-.03em]">{label}</h3><p className="mt-3 max-w-sm text-sm leading-relaxed text-muted-foreground">{text}</p><span className="mt-8 inline-flex items-center gap-2 text-sm font-medium">Ver cómo funciona <ArrowUpRight className="h-4 w-4 transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5"/></span></a>)}</div></section>
    <section className="mt-20 grid grid-cols-1 gap-4 md:mt-28 md:grid-cols-3"><CardPlaceholder label="Tarjeta de sellos" detail="Recompensa visitas recurrentes" tone="mint"/><CardPlaceholder label="Tarjeta por puntos" detail="Acumula y canjea según tus reglas" tone="blue"/><CardPlaceholder label="Tarjeta de evento" detail="Actualiza cada acceso o experiencia" tone="sand"/></section>
    <section className="mt-20 grid grid-cols-1 gap-3 md:mt-28 md:grid-cols-3"><CapabilityBlock number="01" title="Sin app" text="El cliente no descarga nada ni crea otra cuenta para participar."/><CapabilityBlock number="02" title="Siempre disponible" text="El pass vive en el teléfono, se actualiza y puede restaurarse."/><CapabilityBlock number="03" title="Operación simple" text="Puedes comenzar con un QR sin cambiar todo tu sistema de ventas."/></section>
  </PageShell>
}

function Capability({ icon: Icon, text }: { icon: typeof WalletCards; text: string }) { return <div className="flex items-center gap-3"><Icon className="h-4 w-4 text-foreground" strokeWidth={1.5}/>{text}</div> }
function CapabilityBlock({ number, title, text }: { number: string; title: string; text: string }) { return <div className="border-t border-border p-8 md:p-10"><span className="text-xs text-muted-foreground">({number})</span><h3 className="mt-20 text-2xl font-medium">{title}</h3><p className="mt-3 max-w-xs text-sm leading-relaxed text-muted-foreground">{text}</p></div> }

const features = [{ icon: Bell, eyebrow: '01 / Una razón útil', title: 'Haz que una buena visita no se enfríe.', text: 'Tu negocio aparece con un motivo relevante antes de que la siguiente decisión se cierre.', examples: ['“Hoy el segundo café va por la casa.”', '“Happy hour de 18:00 a 20:00.”', '“Tu beneficio sigue activo.”'] }, { icon: Zap, eyebrow: '02 / Una relación que sigue', title: 'Sostén el hábito sin perseguirlo todos los días.', text: 'Los momentos importantes pueden abrir el siguiente paso sin depender de una tarea manual del equipo.', examples: ['Después de la tercera visita → recompensa', '30 días sin visita → motivo para volver', 'Cliente cerca → beneficio relevante'] }, { icon: CircleGauge, eyebrow: '03 / Una decisión mejor', title: 'Repite lo que realmente hace que vuelvan.', text: 'El historial del programa te ayuda a elegir el próximo incentivo con señales reales.', examples: ['Quién está regresando', 'Qué motivo activa una visita', 'Qué beneficio conviene repetir'] }]
export function FeaturesPage() { return <PageShell eyebrow="Resultado / relación que sigue" title={<>La relación sigue<br/><span>cuando se van.</span></>} intro="La tecnología solo importa si ayuda a que una buena visita se convierta en una próxima decisión a favor de tu negocio."><div className="mb-20 grid grid-cols-12 items-center gap-12 border-t border-border pt-20"><div className="col-span-12 md:col-span-5"><PhoneMockup variant="notification" label="Notificación de Fidelio en Wallet"/></div><div className="col-span-12 md:col-span-5 md:col-start-8"><p className="text-[11px] uppercase tracking-[0.2em] text-muted-foreground">El mecanismo es simple</p><h2 className="mt-8 text-4xl font-medium leading-tight">Un motivo aparece cuando todavía puede cambiar el resultado.</h2><p className="mt-6 text-base leading-relaxed text-muted-foreground">La tarjeta, los mensajes y las reglas están ahí para una sola cosa: dar continuidad a una relación que empezó en el local.</p></div></div><div className="grid gap-5">{features.map(({ icon: Icon, eyebrow, title, text, examples }, i) => <section key={eyebrow} className={`grid grid-cols-12 gap-10 rounded-[28px] p-8 md:p-12 ${i % 2 ? 'bg-[#e8ebe4]' : 'bg-foreground text-white'}`}><div className="col-span-12 md:col-span-5"><Icon className={`h-6 w-6 ${i % 2 ? 'text-foreground' : 'text-white'}`} strokeWidth={1.5}/><p className={`mt-16 text-[11px] uppercase tracking-[0.2em] ${i % 2 ? 'text-muted-foreground' : 'text-white/45'}`}>{eyebrow}</p><h2 className="mt-5 text-4xl font-medium leading-tight tracking-[-.03em] md:text-5xl">{title}</h2></div><div className="col-span-12 md:col-span-5 md:col-start-8 md:self-end"><p className={`text-base leading-relaxed ${i % 2 ? 'text-muted-foreground' : 'text-white/55'}`}>{text}</p><div className={`mt-8 border-t pt-5 text-sm leading-loose ${i % 2 ? 'border-foreground/15 text-foreground/65' : 'border-white/15 text-white/55'}`}>{examples.map(example => <p key={example}>{example}</p>)}</div></div></section>)}</div><div className="mt-20 grid grid-cols-1 gap-4 md:grid-cols-2"><ScenePlaceholder label="Foto por incorporar" detail="Cliente real recibiendo un motivo relevante para volver" tone="dark"/><ScenePlaceholder label="Dashboard por incorporar" detail="Captura de retorno y aprendizaje del programa"/></div></PageShell> }

export function IndustriesPage() { return <PageShell eyebrow="Fidelio / Industrias" title={<>La misma meta.<br/><span>Clientes que vuelven.</span></>} intro="Lo que cambia entre una cafetería, un restaurante o un comercio es el momento de compra. El resultado que importa es el mismo: más relaciones que regresan."><div className="grid grid-cols-1 border-t border-border md:grid-cols-2">{industries.map(([name, promise, text], i) => { const slug = Object.entries(industryProfiles).find(([, profile]) => profile.label === name)?.[0]; return <a key={name} href={`#industrias/${slug}`} className="group border-b border-border py-10 md:pr-12"><div className="flex items-start gap-6"><span className="text-xs text-muted-foreground">0{i + 1}</span><div className="flex-1"><div className="flex items-center justify-between gap-6"><h2 className="text-3xl font-medium tracking-[-.025em]">{name}</h2><ArrowUpRight className="h-5 w-5 text-muted-foreground transition group-hover:-translate-y-1 group-hover:translate-x-1"/></div><p className="mt-4 text-lg text-foreground/75">{promise}</p><p className="mt-4 max-w-md text-sm leading-relaxed text-muted-foreground">{text}</p><div className="mt-7 flex flex-wrap gap-2"><span className="rounded-full border border-border px-3 py-1 text-xs text-muted-foreground">Clientes reconocibles</span><span className="rounded-full border border-border px-3 py-1 text-xs text-muted-foreground">Motivos para volver</span><span className="rounded-full border border-border px-3 py-1 text-xs text-muted-foreground">Retorno entendible</span></div></div></div></a> })}</div><div className="mt-20 grid grid-cols-1 gap-4 md:grid-cols-3"><ScenePlaceholder label="Café / caja" detail="Placeholder para cliente usando su tarjeta"/><ScenePlaceholder label="Restaurante / mesa" detail="Placeholder para visita recurrente" tone="dark"/><ScenePlaceholder label="Evento / acceso" detail="Placeholder para pass digital en entrada"/></div><section className="mt-24 grid grid-cols-12 items-center gap-12 border-t border-border pt-20"><div className="col-span-12 md:col-span-5"><p className="text-[11px] uppercase tracking-[0.2em] text-muted-foreground">Para cualquier momento de consumo</p><h2 className="mt-8 text-4xl font-medium leading-tight">Más relaciones.<br/><span className="text-muted-foreground">Más retorno.</span></h2></div><div className="col-span-12 md:col-span-5 md:col-start-8"><p className="text-base leading-relaxed text-muted-foreground">Fidelio no promete una cifra universal. Le da a cada negocio una forma de aprender qué oferta, campaña y momento hacen que su gente vuelva.</p></div></section></PageShell> }

function PageShell({ eyebrow, title, intro, children }: { eyebrow: string; title: ReactNode; intro: string; children: ReactNode }) { return <main className="min-h-screen bg-background px-5 pb-20 pt-28 sm:px-8 md:px-12 md:pb-32 md:pt-36"><div className="grid grid-cols-12 gap-10 pb-16 md:gap-12 md:pb-28"><div className="col-span-12 md:col-span-8"><p className="mb-8 text-[11px] uppercase tracking-[0.2em] text-muted-foreground md:mb-10">{eyebrow}</p><AnimatedHeading as="h1" className="font-display text-[clamp(2.25rem,10vw,3rem)] font-medium leading-[1.01] tracking-[-.04em] md:text-6xl">{title}</AnimatedHeading></div><AnimatedText className="col-span-12 self-end text-base leading-relaxed text-muted-foreground md:col-span-4 md:col-start-9 md:pb-2">{intro}</AnimatedText></div>{children}</main> }
