import { AnimatePresence, motion } from 'motion/react'
import { ArrowLeft, ArrowRight } from 'lucide-react'
import { useState } from 'react'
import { MaskedImage } from './AnimatedHeading'
import type { ReactNode } from 'react'

const BASE = 'https://qclay.design/lovable/pelmatech/'
const team = [{ img: 'blur-doctor.png', role: 'SURGEON GENERAL', name: 'Dr. Helga Brooks' }, { img: 'happy-doctor.png', role: 'PEDIATRICIAN', name: 'Dr. Kwame Mbeki' }, { img: 'young-doctor.png', role: 'THERAPIST', name: 'Dr. Matteo Dubois' }, { img: 'happy-doctor.png', role: 'NEUROLOGIST', name: 'Dr. Hana Sato' }, { img: 'blur-doctor.png', role: 'CARDIOLOGIST', name: 'Dr. Aria Vance' }]
export function TeamCarousel({ intro }: { intro: ReactNode }) {
  const [index, setIndex] = useState(0); const [hovered, setHovered] = useState(false); const GAP = 11.26; const visible = 3.25; const maxIndex = Math.max(0, Math.ceil(team.length - visible))
  return <div className="relative" onMouseEnter={() => setHovered(true)} onMouseLeave={() => setHovered(false)}><div className="flex gap-[11.26px]"><div className="w-[324px] shrink-0">{intro}</div><div className="relative min-w-0 flex-1 overflow-hidden"><motion.div className="flex" style={{ gap: GAP, width: `calc(${team.length} * ((100% - ${(visible - 1) * GAP}px) / ${visible}) + ${(team.length - 1) * GAP}px)` }} animate={{ x: `calc(${-index} * (100% + ${GAP}px) / ${team.length})` }} transition={{ duration: .7, ease: [.22, 1, .36, 1] }}>{team.map((member, i) => <div key={member.name} className="w-[calc((100%_-_45.04px)_/_5)] shrink-0" style={{ fontFamily: '"TT Hoves", "Helvetica Neue", Helvetica, Arial, sans-serif' }}><div className="aspect-[3/4] overflow-hidden bg-muted"><MaskedImage src={`${BASE}${member.img}`} alt={member.name} delay={i * .08}/></div><div className="pt-6"><p className="text-xs tracking-[0.2em] text-muted-foreground">{member.role}</p><p className="mt-2 text-xl font-medium">{member.name}</p></div></div>)}</motion.div><AnimatePresence>{hovered && <motion.div className="absolute left-1/2 top-[35%] z-10 -translate-x-1/2 -translate-y-1/2" initial={{ opacity: 0, scale: .85 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: .85 }} transition={{ duration: .25 }}><div className="flex h-[126px] w-[126px] items-center justify-center gap-4 rounded-full" style={{ background: 'rgba(72,72,72,.16)', backdropFilter: 'blur(84px)', WebkitBackdropFilter: 'blur(84px)' }}><button className="cursor-pointer text-white transition disabled:cursor-default disabled:opacity-30" disabled={index === 0} onClick={() => setIndex(i => Math.max(0, i - 1))}><ArrowLeft className="h-7 w-7"/></button><button className="cursor-pointer text-white transition disabled:cursor-default disabled:opacity-30" disabled={index >= maxIndex} onClick={() => setIndex(i => Math.min(maxIndex, i + 1))}><ArrowRight className="h-7 w-7"/></button></div></motion.div>}</AnimatePresence></div></div></div>
}
